#!/bin/bash
set -e

docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID         \
                -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                -e GPG_RECIPIENT=$GPG_RECIPIENT                 \
                -e UPLOAD_BUCKET=$UPLOAD_BUCKET                 \
                -e UPLOAD_PREFIX=$UPLOAD_PREFIX                 \
                -e KEY_SERVER=$KEY_SERVER                       \
                -e KEY_HASH=$KEY_HASH                           \
                -p 22 -p 8080:8080 test
